# Generated by Django 6.0 on 2026-01-22 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('telefone_responsavel', models.CharField(max_length=15, verbose_name='Responsável Telefone')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('tipo', models.IntegerField(choices=[(1, 'Comportamento'), (2, 'Saúde'), (3, 'Convivência'), (4, 'Acidente')], verbose_name='Tipo')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('situacao', models.IntegerField(choices=[(1, 'Aguardando análise'), (2, 'Ação pedagógica realizada'), (3, 'Finalizada')], verbose_name='Situação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.matricula', verbose_name='Matrícula')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('codigo_turma', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('serie_ano', models.IntegerField(verbose_name='Série/Ano')),
                ('ano_letivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('ue', models.ForeignKey(db_column='codigo_ue', on_delete=django.db.models.deletion.CASCADE, to='sme.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(db_column='codigo_turma', on_delete=django.db.models.deletion.CASCADE, to='gestao.turma', verbose_name='Turma'),
        ),
    ]
