# Generated by Django 6.0 on 2026-01-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_ocorrencia_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Aguardando análise'), (2, 'Ação pedagógica realizada'), (3, 'Finalizada')], verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Comportamento'), (2, 'Saúde'), (3, 'Convivência'), (4, 'Acidente')], verbose_name='Tipo'),
        ),
    ]
