# Generated by Django 6.0 on 2026-01-15 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('situacao', models.IntegerField(verbose_name='Situação')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.matricula', verbose_name='Matrícula')),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'db_table': 'ocorrencias',
            },
        ),
    ]
