# Generated by Django 6.0 on 2026-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.IntegerField(verbose_name='Tipo'),
        ),
    ]
