# Generated by Django 6.0 on 2026-01-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('telefone_responsavel', models.CharField(max_length=15, verbose_name='Responsável Telefone')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Dre',
            fields=[
                ('codigo_dre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo DRE')),
                ('nome', models.CharField(max_length=100, verbose_name='DRE')),
                ('abreviacao', models.CharField(max_length=10, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'DRE',
                'verbose_name_plural': 'DREs',
                'db_table': 'dres',
            },
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('codigo_ue', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo UE')),
                ('nome', models.CharField(max_length=100, verbose_name='UE')),
                ('dre', models.OneToOneField(db_column='codigo_dre', on_delete=django.db.models.deletion.CASCADE, to='sme.dre', verbose_name='DRE')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UEs',
                'db_table': 'ues',
            },
        ),
    ]
