# Generated by Django 6.0 on 2026-01-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dre',
            fields=[
                ('codigo_dre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('abreviacao', models.CharField(max_length=10, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'DRE',
                'verbose_name_plural': 'DREs',
            },
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('codigo_ue', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='UE')),
                ('dre', models.OneToOneField(db_column='codigo_dre', on_delete=django.db.models.deletion.CASCADE, to='sme.dre', verbose_name='DRE')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UEs',
            },
        ),
    ]
