# Generated by Django 6.0 on 2026-01-15 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='codigo_dre',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='dre',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='codigo_ue',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('codigo_turma', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('serie_ano', models.IntegerField(verbose_name='Série/Ano')),
                ('ano_letivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('ue', models.ForeignKey(db_column='codigo_ue', on_delete=django.db.models.deletion.CASCADE, to='sme.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
            },
        ),
    ]
