# Generated by Django 6.0 on 2026-01-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_alter_dre_codigo_dre_alter_dre_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
